Repository project-codeflare/appwrapper, pull requests merged in 2024-07, with the labels that each got.

#184 Flexible configuration of Kueue's GenericJob Reconciller
  pkg/config/config.go
  pkg/controller/setup.go
Labels: bug

#186 remove ChildAdmissionController only needed by Kueue 0.6
  config/default/config.yaml
  config/dev/config.yaml
  internal/controller/appwrapper/resource_management.go
  internal/controller/workload/child_admission_controller.go
  pkg/config/config.go
  pkg/controller/setup.go
Labels: enhancement

#189 update CI to use kind v0.23.0
  hack/e2e-util.sh
  hack/kind-config.yaml
Labels: housekeeping

#190 use kustomize to deploy/configure Kueue instead of patching manifest
  hack/deploy-kueue.sh
  hack/kueue-config/controller_manager_config.yaml
  hack/kueue-config/kustomization.yaml
  hack/kueue-patches/01-manage-all-jobs.txt
  hack/kueue-patches/02-aw-external-frameworks.txt
Labels: housekeeping

#192 prepare for 0.21.0 release
  README.md
  docs/release_instructions.md
  site/_config.yml
  site/_pages/quick-start.md
Labels: housekeeping

#198 Autopilot: auto-injection of Node anti-affinities
  internal/controller/appwrapper/resource_management.go
  pkg/config/config.go
Labels: enhancement

#204 Add Autopilot documentation to website
  README.md
  site/_pages/arch-fault-tolerance.md
  site/_pages/overview.md
Labels: housekeeping

#205 fix incorrect link
  README.md
Labels: housekeeping

#215 add reminder to check PR labels before tagging release
  docs/release_instructions.md
Labels: housekeeping

#218 Distinguish NoSchedule and NoExecute Autopilot labels
  internal/controller/appwrapper/appwrapper_controller.go
  internal/controller/appwrapper/node_health_monitor.go
  internal/controller/appwrapper/node_health_monitor_test.go
  internal/controller/appwrapper/resource_management.go
  pkg/config/config.go
  pkg/controller/setup.go
  site/_pages/arch-fault-tolerance.md
  test/e2e/appwrapper_test.go
Labels: enhancement
