Repository project-codeflare/appwrapper, pull requests merged in 2024-06, with the labels that each got.

#147 Avoid storing PodSet inference results in Spec
  api/v1beta2/appwrapper_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/workload.codeflare.dev_appwrappers.yaml
  internal/controller/appwrapper/appwrapper_controller.go
  internal/controller/appwrapper/fixtures_test.go
  internal/controller/appwrapper/resource_management.go
  internal/controller/appwrapper/suite_test.go
  internal/controller/awstatus/status_utils.go
  internal/controller/workload/child_admission_controller.go
  internal/controller/workload/workload_controller.go
  internal/webhook/appwrapper_fixtures_test.go
  internal/webhook/appwrapper_webhook.go
  internal/webhook/appwrapper_webhook_test.go
  pkg/controller/setup.go
  pkg/utils/utils.go
  test/e2e/appwrapper_test.go
  test/e2e/fixtures_test.go
Labels: enhancement

#152 CI: LABEL_FILTER not relevant for setting up test cluster
  .github/workflows/CI.yaml
Labels: housekeeping

#153 release prep: bump version number in docs
  README.md
  site/_config.yml
Labels: housekeeping

#154 Ensure label map is not nil
  internal/webhook/appwrapper_webhook.go
Labels: bug

#155 Add test for default queue name injection
  internal/webhook/appwrapper_webhook_test.go
  internal/webhook/suite_test.go
Labels: housekeeping

#156 release prep: bump version number in docs
  README.md
  site/_config.yml
Labels: housekeeping

#158 Pods being deleted should not be counted as healthy running pods.
  internal/controller/appwrapper/appwrapper_controller.go
Labels: bug

#159 don't count components that are being deleted as deployed
  internal/controller/appwrapper/appwrapper_controller.go
Labels: bug

#160 prepare for 0.13.2 release
  README.md
  site/_config.yml
Labels: housekeeping

#163 Recognize failed PyTorchJobs and skip pod-level gracePeriod
  internal/controller/appwrapper/appwrapper_controller.go
  samples/wrapped-failing-pytorch-job.yaml
Labels: enhancement

#167 Fix apigroup for raycluster in RBAC-generation annotation
  config/rbac/role.yaml
  internal/controller/appwrapper/appwrapper_controller.go
Labels: bug

#170 bug fix: ensure ComponentStatus is initialized in ExpectedPodCount
  internal/controller/appwrapper/appwrapper_controller.go
  internal/controller/appwrapper/appwrapper_controller_test.go
  internal/controller/awstatus/status_utils.go
  internal/controller/workload/workload_controller.go
  pkg/utils/utils.go
  test/e2e/util_test.go
Labels: bug

#169 CI improvement: if printing appwrapper-manager logs, also print Kueue-manager logs
  hack/e2e-util.sh
Labels: housekeeping

#166 component-level failure detection for RayCluster and RayJob
  internal/controller/appwrapper/appwrapper_controller.go
Labels: enhancement

#175 release prep: v0.20.1
  README.md
  site/_config.yml
Labels: housekeeping

#176 enable testing on pushes to rhoai-2.10 branch
  .github/workflows/CI-standalone.yaml
  .github/workflows/CI.yaml
Labels: housekeeping

#178 enable testing on PRs and pushes to rhoai-2.10 branch (#176)
  .github/workflows/CI-standalone.yaml
  .github/workflows/CI.yaml
Labels: housekeeping

#177 Disable component-level failure detection for Ray (#174)
  internal/controller/appwrapper/appwrapper_controller.go
Labels: bug

#180 ensure AppWrapper controller sets PodsReady condition on Workload
  pkg/controller/setup.go
Labels: bug

#181 prep for 0.20.2 release
  README.md
  site/_config.yml
Labels: housekeeping

#182 ensure AppWrapper controller sets PodsReady condition on Workload (#180)
  pkg/controller/setup.go
Labels: bug, cherry-pick
