Repository project-codeflare/appwrapper, pull requests merged in 2024-05, with the labels that each got.

#126 only put 1 copy of the CRD in install.yaml
  Makefile
Labels: bug

#127 implement shorter warmup grace period on pods being admitted
  api/v1beta2/appwrapper_types.go
  internal/controller/appwrapper/appwrapper_controller.go
  pkg/config/config.go
  site/_pages/arch-fault-tolerance.md
Labels: enhancement

#133 release prep: bump version number in doc
  README.md
  site/_config.yml
Labels: housekeeping

#134 Move nodeSelector to spec
  internal/controller/appwrapper/resource_management.go
Labels: bug

#135 Add schedulerName option and injection logic
  internal/controller/appwrapper/resource_management.go
  pkg/config/config.go
Labels: enhancement

#136 release prep: bump version number in doc
  README.md
  site/_config.yml
Labels: housekeeping

#139 track status of each deployed component in AppWrapper Status
  api/v1beta2/appwrapper_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/workload.codeflare.dev_appwrappers.yaml
  internal/controller/appwrapper/appwrapper_controller.go
  internal/controller/appwrapper/resource_management.go
Labels: enhancement

#141 Detect missing Component and transition to Failed state
  internal/controller/appwrapper/appwrapper_controller.go
  internal/controller/appwrapper/appwrapper_controller_test.go
  test/e2e/appwrapper_test.go
Labels: enhancement

#143 Copy PodTemplate defaulter from Kubernetes to avoid dependency
  go.mod
  go.sum
  pkg/utils/defaulter.go
  pkg/utils/utils.go
Labels: bug

#145 cleanup whitespace/deadcode -- no real change
  pkg/utils/defaulter.go
Labels: housekeeping
