Repository project-codeflare/appwrapper, pull requests merged in 2024-08, with the labels that each got.

#225 Upgrade to Kueue 0.8.0
  go.mod
  go.sum
  hack/kueue-config/kustomization.yaml
Labels: enhancement

#226 tweak ft docs
  site/_pages/arch-fault-tolerance.md
Labels: housekeeping

#227 Use Patch operations to update AppWrapper.Status
  internal/controller/appwrapper/appwrapper_controller.go
  internal/controller/appwrapper/resource_management.go
Labels: enhancement

#228 inject AppWrapper finalizer in WebHook
  internal/controller/appwrapper/appwrapper_controller.go
  internal/webhook/appwrapper_webhook.go
Labels: enhancement

#229 clarify comment on finalizer addition
  internal/controller/appwrapper/appwrapper_controller.go
Labels: housekeeping

#232 Get dev mode (make run) working again
  internal/controller/appwrapper/appwrapper_controller.go
  internal/webhook/appwrapper_webhook.go
Labels: bug

#238 add GitHub link to website navigation
  site/_data/navigation.yml
Labels: housekeeping

#239 account for all covered resources when a node is cordoned
  internal/controller/appwrapper/node_health_monitor.go
Labels: bug

#240 prepare for 0.24 release
  README.md
  site/_config.yml
Labels: housekeeping

#242 Add age printcolumn
  api/v1beta2/appwrapper_types.go
Labels: enhancement
