Repository project-codeflare/appwrapper, pull requests merged in 2024-04, with the labels that each got.

#72 give each controller a unique names for cleaner log output
  internal/controller/appwrapper/appwrapper_controller.go
  internal/controller/workload/child_admission_controller.go
  internal/controller/workload/workload_controller.go
Labels: bug

#76 Create jekyll-gh-pages.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: housekeeping

#77 fine tune github actions for gh-pages configuration
  .github/workflows/CI-standalone.yaml
  .github/workflows/CI.yaml
  .github/workflows/jekyll-gh-pages.yml
Labels: housekeeping

#78 fix upload action
  .github/workflows/jekyll-gh-pages.yml
Labels: housekeeping

#79 debug page action
  .github/workflows/jekyll-gh-pages.yml
Labels: housekeeping

#80 gh repo metadata for jekyll production build
  site/_config.yml
Labels: housekeeping

#81 add mermaid support to gh pages build
  site/Gemfile
  site/_config.yml
  site/_pages/architecture.md
Labels: housekeeping

#82 first cut at minimal website
  site/_config.yml
  site/_data/navigation.yml
  site/_pages/arch-controller.md
  site/_pages/arch-crd.md
  site/_pages/arch-fault-tolerance.md
  site/_pages/dev-setup.md
  site/_pages/quick-start.md
Labels: housekeeping

#83 quick start instructions in website
  docs/release_instructions.md
  site/_config.yml
  site/_pages/quick-start.md
Labels: housekeeping

#86 pull website instructions out of site dir to avoid confusing the build
  docs/website_instructions.md
  site/README.md
Labels: housekeeping

#88 fix some typos in webpages
  site/_pages/dev-setup.md
  site/_pages/quick-start.md
Labels: housekeeping

#90 web page: first cut at generated API references
  Makefile
  site/_data/navigation.yml
  site/_pages/appwrapper.v1beta2.md
  site/genref/config.yaml
  site/genref/markdown/members.tpl
  site/genref/markdown/pkg.tpl
  site/genref/markdown/type.tpl
Labels: housekeeping

#93 copy edit pass on arch-controller.md
  site/_pages/arch-controller.md
Labels: housekeeping

#98 detect missing podSetInfo and raise fatal error
  internal/controller/appwrapper/resource_management.go
Labels: bug

#100 config cleanup; remove unused certmanager config/patches
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_appwrappers.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/standalone/kustomization.yaml
  config/standalone/webhookcainjection_patch.yaml
Labels: housekeeping

#101 revert Dockerfile back to defining an entrypoint
  Dockerfile
Labels: housekeeping

#104 make deploy is sufficient
  .github/workflows/CI-standalone.yaml
  .github/workflows/CI.yaml
Labels: housekeeping

#105 propagate BUILD_VERSION and BUILD_DATE to docker build/buildx
  Dockerfile
  Makefile
Labels: bug

#106 update docs for 0.8.0 release
  README.md
  site/_config.yml
Labels: housekeeping

#111 add list annotations to Conditions array
  api/v1beta2/appwrapper_types.go
  config/crd/bases/workload.codeflare.dev_appwrappers.yaml
Labels: housekeeping

#113 Fix bug in getValueAtPath for array index expression
  pkg/utils/utils.go
Labels: bug

#108 Infer pod sets for known GVKs
  internal/webhook/appwrapper_fixtures_test.go
  internal/webhook/appwrapper_webhook.go
  internal/webhook/appwrapper_webhook_test.go
  pkg/utils/utils.go
Labels: enhancement

#115 Record user name and id as AppWrapper labels
  internal/webhook/appwrapper_webhook.go
  internal/webhook/appwrapper_webhook_test.go
  internal/webhook/suite_test.go
Labels: enhancement

#120 release prep: bump version number to v0.10.0 in docs
  README.md
  site/_config.yml
Labels: housekeeping

#122 use unique names in samples
  samples/wrapped-failing-job.yaml
  samples/wrapped-failing-pod.yaml
Labels: housekeeping

#123 detect when a preexisting resource is not controlled by the appwrapper
  internal/controller/appwrapper/resource_management.go
Labels: bug

#124 Configurable automatic deletion of resources for Succeeded AppWrappers
  api/v1beta2/appwrapper_types.go
  internal/controller/appwrapper/appwrapper_controller.go
  pkg/config/config.go
  samples/wrapped-job.yaml
  site/_pages/arch-controller.md
  site/_pages/arch-fault-tolerance.md
Labels: enhancement
